const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

/**
 * Code Model
 * Maps to legacy app_codes table
 * Stores authentication codes generated by clinics/doctors for patients
 */
const Code = sequelize.define('Code', {
  id: {
    type: DataTypes.BIGINT,
    primaryKey: true,
    autoIncrement: true
  },
  businessId: {
    type: DataTypes.BIGINT,
    allowNull: false,
    field: 'business_id'
  },
  codFisc: {
    type: DataTypes.STRING,
    allowNull: true,
    field: 'cod_fisc'
  },
  code: {
    type: DataTypes.STRING,
    allowNull: true
  },
  dataRequest: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'data_request'
  },
  used: {
    type: DataTypes.CHAR(1),
    allowNull: true,
    defaultValue: 'N'
  },
  name: {
    type: DataTypes.STRING,
    allowNull: true
  },
  surname: {
    type: DataTypes.STRING,
    allowNull: true
  }
}, {
  tableName: 'app_codes',
  timestamps: false
});

module.exports = Code;
